name: nostalgia_brawl
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Engine de jogos 2D
  flame: ^1.14.0

  # Gerenciamento de estado
  flutter_bloc: ^8.1.3

  # Animações vetoriais com Rive
  rive: ^0.12.3

  # Áudio (efeitos e música de fundo)
  audioplayers: ^5.2.1

  # Armazenamento local
  shared_preferences: ^2.2.2

  # Ícones estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/characters/
    - assets/backgrounds/
    - assets/audio/
    - assets/fonts/
